<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\KolProdiController;
use App\Http\Controllers\KolJurusanController;
use App\Http\Controllers\KolJurusanSekolahController;
use App\Http\Controllers\KolJkController;
use App\Http\Controllers\KolKabupatenController;
use App\Http\Controllers\KolProvinsiController;
use App\Http\Controllers\KolWilayahController;
use App\Http\Controllers\KolStatusHidupController;
use App\Http\Controllers\KolAgamaController;
use App\Http\Controllers\KolDarahController;
use App\Http\Controllers\KolPekerjaanController;
use App\Http\Controllers\KolPenghasilanController;
use App\Http\Controllers\KolStatusSipilController;
use App\Http\Controllers\KolHubunganController;
use App\Http\Controllers\KolAsalSekolahController;
use App\Http\Controllers\KolBebasYudisiumController;
use App\Http\Controllers\KolBidangSekolahController;
use App\Http\Controllers\KolBulanController;
use App\Http\Controllers\KolJalurPmbController;
use App\Http\Controllers\KolJenisAktifitasController;
use App\Http\Controllers\KolJenisEvaluasiController;
use App\Http\Controllers\KolJenisMkController;
use App\Http\Controllers\KolJenisSekolahController;
use App\Http\Controllers\KolJenisSkController;
use App\Http\Controllers\KolJenisSuratOnlineController;
use App\Http\Controllers\KolJenjangPoliteknikController;
use App\Http\Controllers\KolPendidikanController;
use App\Http\Controllers\KolPilihanProdiSbmpnController;
use App\Http\Controllers\KolPoliteknikController;
use App\Http\Controllers\KolProdiPoliteknikController;
use App\Http\Controllers\KolProgramSekolahController;
use App\Http\Controllers\KolSkemaLspController;
use App\Http\Controllers\KolStatusController;
use App\Http\Controllers\KolStatusKalenderController;
use App\Http\Controllers\KolStatusKeluargaController;
use App\Http\Controllers\KolStatusStrukturalController;
use App\Http\Controllers\KolTerminalController;
use App\Http\Controllers\KolPilihanProdiController;
use App\Http\Controllers\KategoriUKTController;
use App\Http\Controllers\KeuTagihanController;
use App\Http\Controllers\KeuKeringananController;

Route::apiResource('kategori-ukt', KategoriUKTController::class);
Route::apiResource('tagihan', KeuTagihanController::class);
Route::apiResource('keringanan', KeuKeringananController::class);
Route::get('tagihan/{id}/nominal-akhir', [\App\Http\Controllers\KeuTagihanController::class, 'nominalAkhir']);
Route::apiResource('kol-pilihan-prodi', KolPilihanProdiController::class);
// Routes untuk kol_* (master data)
Route::apiResource('kol-prodi', KolProdiController::class);
Route::apiResource('kol-jurusan', KolJurusanController::class);
Route::apiResource('kol-jurusan-sekolah', KolJurusanSekolahController::class);
Route::apiResource('kol-jk', KolJkController::class);
Route::apiResource('kol-kabupaten', KolKabupatenController::class);
Route::apiResource('kol-provinsi', KolProvinsiController::class);
Route::apiResource('kol-wilayah', KolWilayahController::class);
Route::apiResource('kol-status-hidup', KolStatusHidupController::class);

Route::apiResource('kol-hubungan', KolHubunganController::class);
Route::apiResource('kol-agama', KolAgamaController::class);
Route::apiResource('kol-darah', KolDarahController::class);
Route::apiResource('kol-pekerjaan', KolPekerjaanController::class);
Route::apiResource('kol-penghasilan', KolPenghasilanController::class);
Route::apiResource('kol-status-sipil', KolStatusSipilController::class);
Route::apiResource('kol-hubungan', KolHubunganController::class);

Route::apiResource('kol-asal-sekolah', KolAsalSekolahController::class);
Route::apiResource('kol-bebas-yudisium', KolBebasYudisiumController::class);
Route::apiResource('kol-bidang-sekolah', KolBidangSekolahController::class);
Route::apiResource('kol-bulan', KolBulanController::class);
Route::apiResource('kol-jalur-pmb', KolJalurPmbController::class);
Route::apiResource('kol-jenis-aktifitas', KolJenisAktifitasController::class);
Route::apiResource('kol-jenis-evaluasi', KolJenisEvaluasiController::class);
Route::apiResource('kol-jenis-mk', KolJenisMkController::class);
Route::apiResource('kol-jenis-sekolah', KolJenisSekolahController::class);
Route::apiResource('kol-jenis-sk', KolJenisSkController::class);
Route::apiResource('kol-jenis-surat-online', KolJenisSuratOnlineController::class);
Route::apiResource('kol-jenjang-politeknik', KolJenjangPoliteknikController::class);

Route::apiResource('kol-pilihanprodi-sbmpn', KolPilihanProdiSbmpnController::class);
Route::apiResource('kol-politeknik', KolPoliteknikController::class);
Route::apiResource('kol-prodi-politeknik', KolProdiPoliteknikController::class);
Route::apiResource('kol-program-sekolah', KolProgramSekolahController::class);
Route::apiResource('kol-skema-lsp', KolSkemaLspController::class);
Route::apiResource('kol-status', KolStatusController::class);
Route::apiResource('kol-status-kalender', KolStatusKalenderController::class);
Route::apiResource('kol-status-keluarga', KolStatusKeluargaController::class);
Route::apiResource('kol-status-struktural', KolStatusStrukturalController::class);
Route::apiResource('kol-terminal', KolTerminalController::class);
Route::apiResource('kol-pilihan-prodi', KolPilihanProdiController::class);
Route::apiResource('kol-pendidikan', KolPendidikanController::class);